services:
  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    container_name: angular_dev
    user: '1000:1000'
    ports:
      - '4200:4200'
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - tinysplit-api_api-network
    environment:
      - CHOKIDAR_USEPOLLING=true

networks:
  tinysplit-api_api-network:
    external: true
    driver: bridge
